- hosts: all
  tasks:
    - package: "name=httpd state=present"
    - copy: "content='Hello!! There How Are you , This is my own Server testing /n from UDIT RAJ PARIHAR' dest=/var/www/html/index.html"
    - service: "name=httpd state=started"
  
